name: Use Case Workflows

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - run: cd ./src/WebApplication1
      - name: Restore
        run: dotnet restore ./src/WebApplication1
      - name: Build
        run: dotnet build ./src/WebApplication1
      - name: Publish
        run: dotnet publish ./src/WebApplication1 --no-build --output ./artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ./artifacts
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - run: cd ./src/WebApplication1
      - name: Restore
        run: dotnet restore ./src/TestProject1
      - name: Test
        run: dotnet test ./src/TestProject1
  build-docker:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: ./artifacts
      - name: docker login
        uses: docker/login-action@v2
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.PAT }}
      - name: Build Docker image
        run: docker build -t ghcr.io/leandro-melloni/use-case-workflows:latest .
      - name: Push Docker image
        run: docker push ghcr.io/leandro-melloni/use-case-workflows:latest