name: Use Case Workflows

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - run: cd ./src/webApplication1
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Publish
        run: dotnet publish --no-build --output ./artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ./artifacts